- debug: msg="Applying slave configuration on {{inventory_hostname}} with IP address {{ansible_ssh_host}}"

- name: "Apply postgresql.conf"
  shell: "cp /vagrant/conf/slave-postgresql.conf /etc/postgresql/9.1/main/postgresql.conf"

- name: "Stop PostgreSQL"
  shell: "service postgresql stop"
